new-features
Meltzli/PhotographerWeb pull request #8
Opened 2023-06-18 21:22 UTC by Meltzli

2023-06-19 06:18 UTC, wecoastca requested changes

2023-06-19 06:18 UTC, wecoastca commented on src/App.js
> +export default App;
зачем наверх перенес?

2023-06-19 06:18 UTC, wecoastca commented on src/Header/Header.js
> +    WorksRef.current?.scrollIntoView({ behavior: "smooth" });
worksRef при клике по контактам? уверен? проверь как работает

2023-06-19 06:18 UTC, wecoastca commented on src/Layout/Layout.js
> +  const PhotoAboutRef = useRef(null);
все переменные нужно писать с маленькой буквы

2023-06-19 06:18 UTC, wecoastca commented on src/Layout/Layout.js
> +        PhotoAboutRef={PhotoAboutRef}
пропсы тоже должны быть с маленькой буквы. с большой называются только компоненты

2023-06-22 20:46 UTC, wecoastca commented on src/Contacts/Contacts.css
> +.PhotoVK:hover {
видишь св-ва дублируются, создавай отдельный класс

2023-06-22 20:46 UTC, wecoastca commented on src/Header/Header.css
> +  animation: NavButtonAnimation 10s ease infinite;
за анимацию лайк

2023-06-22 20:46 UTC, wecoastca commented on src/Header/Header.js
> +            {" "}
то что форматтер при сохранении автоматом добавляет пустые строки в jsx, убирай их, они не нужны

2023-06-22 20:46 UTC, wecoastca commented on src/Header/Header.js
> +            {" "}
везде

2023-06-22 20:46 UTC, wecoastca commented on src/PhotoAbout/PhotoAbout.css
> +  font-family: "Times New Roman", Times, serif;
font-family лучше добавлять либо для всей страницы, либо для очень больших блоков

2023-06-22 21:25 UTC, Meltzli reviewed
Добавил более менее нормальный зум для кнопок хэдера

2023-06-23 07:28 UTC, merged